/*
 * Aspose OCR Cloud 5.0 API
 *
 * Aspose OCR Cloud 5.0 API
 *
 * The version of the OpenAPI document: 5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Aspose.OCR.Cloud.SDK.Client.OpenAPIDateConverter;

namespace Aspose.OCR.Cloud.SDK.Model
{
    /// <summary>
    /// Represents information about strict regions to recognize text
    /// </summary>
    [DataContract(Name = "OCRRegion")]
    public partial class OCRRegion : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OCRRegion" /> class.
        /// </summary>
        /// <param name="rect">rect.</param>
        /// <param name="order">The serial number of the region for the formation of the text.</param>
        public OCRRegion(OCRRect rect = default(OCRRect), int order = default(int))
        {
            this.Rect = rect;
            this.Order = order;
        }

        /// <summary>
        /// Gets or Sets Rect
        /// </summary>
        [DataMember(Name = "rect", EmitDefaultValue = false)]
        public OCRRect Rect { get; set; }

        /// <summary>
        /// The serial number of the region for the formation of the text
        /// </summary>
        /// <value>The serial number of the region for the formation of the text</value>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public int Order { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OCRRegion {\n");
            sb.Append("  Rect: ").Append(Rect).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
